
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dubbo
    username: root
    password: root
  dubbo:
    application:
      name: robot_user
    registry:
      address: zookeeper://192.168.23.135:2181
    protocol:
      name: dubbo
      port: 20881
    base-package: com.baizhi.service

mybatis:
  mapper-locations: classpath:com/baizhi/mapper/*.xml
server:
  port: 8989
